name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.36
  marquee: ^2.3.0
  audio_video_progress_bar: ^2.0.3
  lottie: ^2.7.0
  permission_handler: ^11.3.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  on_audio_query: ^2.9.0 


  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/constant/

  fonts:
    - family: primary
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
    - family: secondary
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
